# Generated by Django 5.2.11 on 2026-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('no_of_courses', models.IntegerField()),
            ],
        ),
    ]
